name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev-toolchain:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base clang git

    - name: Prepare vanilla sdk
      run: |
        ./build.sh
