name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev-toolchain:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base clang git

    - name: Prepare vanilla sdk
      run: |
        ./build.sh
        
    # - name: Compile samples
    #   if: ${{ success() }}
    #   run: |
    #     cp -rv $PS2SDK/samples ~/
    #     make -C ~/samples
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: sdkvanilla-${{ steps.slug.outputs.sha8 }}
        path: /usr/local/orbisdev
