# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  workflow_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.GITHUB_REPOSITORY }}
        tags: latest
        build_args: BASE_DOCKER_IMAGE=${{ github.repository_owner }}/orbisdev-toolchain:latest
    
    - name: Send Compile action
      run: |
        export DISPATCH_ACTION="$(echo run_build)"
        echo "::set-env name=NEW_DISPATCH_ACTION::$DISPATCH_ACTION"

    - name: Repository Dispatch to liborbis
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ github.repository_owner }}/orbisdev-liborbis
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}"}'
